# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f693150a548dc09c181c14709e229f02bfd96333157b43780132d24b7a62c8787ade32c8200212463e2e17d390983368eba3087ed91c7d77d80f792ce0b76dfb

test:
  secret_key_base: bd2e12cc4df5473a89854426d1b90f0afc0d33d9abf16e94cbc3e68165ce8dcb14ccd0dde47de65bd844ec8c0308d8ea9702e3af90673219d6071d92d235e9b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
